# Generated by Django 3.2 on 2021-04-30 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossRefDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Cross Reference Database',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('entrez', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('systematic_name', models.CharField(db_index=True, max_length=32)),
                ('standard_name', models.CharField(max_length=32, null=True)),
                ('description', models.TextField()),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisms.organism')),
            ],
            options={
                'ordering': ['organism', 'systematic_name'],
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.gene')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisms.organism')),
            ],
        ),
        migrations.CreateModel(
            name='CrossRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xrid', models.CharField(max_length=32)),
                ('crossrefdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.crossrefdb')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.gene')),
            ],
            options={
                'unique_together': {('xrid', 'crossrefdb')},
            },
        ),
    ]
