# Generated by Django 3.2 on 2021-05-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(max_length=16)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.gene')),
            ],
            options={
                'unique_together': {('gene', 'chromosome')},
            },
        ),
    ]
