# Generated by Django 3.2 on 2021-05-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0002_geneinterval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneinterval',
            name='chromosome',
            field=models.CharField(choices=[('chr1', 'chromosome 1'), ('chr2', 'chromosome 2'), ('chr3', 'chromosome 3'), ('chr4', 'chromosome 4'), ('chr5', 'chromosome 5'), ('chr6', 'chromosome 6'), ('chr7', 'chromosome 7'), ('chr8', 'chromosome 8'), ('chr9', 'chromosome 9'), ('chr10', 'chromosome 10'), ('chr11', 'chromosome 11'), ('chr12', 'chromosome 12'), ('chr13', 'chromosome 13'), ('chr14', 'chromosome 14'), ('chr15', 'chromosome 15'), ('chr16', 'chromosome 16'), ('chr17', 'chromosome 17'), ('chr18', 'chromosome 18'), ('chr19', 'chromosome 19'), ('chr20', 'chromosome 20'), ('chr21', 'chromosome 21'), ('chr22', 'chromosome 22'), ('chrX', 'chromosome X'), ('chrY', 'chromosome Y')], max_length=6),
        ),
    ]
